project_name: git-auto-sync

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - binary: git-auto-sync
    id: git-auto-sync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64

  - binary: git-auto-sync-daemon
    id: git-auto-sync-daemon
    dir: daemon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64

  # Macos build needs to be built on macos
  # https://github.com/rjeczalik/notify/issues/177
  - binary: git-auto-sync
    id: git-auto-sync-macos
    env:
      - CGO_ENABLED=1
      - CC=clang
      - CXX=clang++
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - binary: git-auto-sync-daemon
    id: git-auto-sync-daemon-macos
    dir: daemon
    env:
      - CGO_ENABLED=1
      - CC=clang
      - CXX=clang++
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - README.md
      - completions/bash_autocomplete
      - completions/zsh_autocomplete
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: git-auto-sync
    homepage: https://github.com/GitJournal/git-auto-sync
    license: Apache-2.0
    tap:
      owner: GitJournal
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    install: |
      bin.install "git-auto-sync"
      bin.install "git-auto-sync-daemon"
      bash_completion.install "completions/bash_autocomplete"
      zsh_completion.install "completions/zsh_autocomplete"

snapcrafts:
  - publish: true
    summary: Automatically sync your changes in any git repository
    description: |
      GitAutoSync is a simple command line program to automatically commit changes
      to your git repo, and always keep that repo up to date. This way you can use
      any editor with your text files, and never need to worry about committing
      and remembering to push and pull changes.
    confinement: classic
    license: Apache-2.0
    base: core20
    grade: stable
    apps:
      git-auto-sync:
        command: git-auto-sync
        completer: completions/bash_autocomplete

nfpms:
  - id: linux_packages
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    description: |
      GitAutoSync is a simple command line program to automatically commit changes
      to your git repo, and always keep that repo up to date. This way you can use
      any editor with your text files, and never need to worry about committing
      and remembering to push and pull changes.
    homepage: https://github.com/GitJournal/git-auto-sync
    license: Apache-2.0
    maintainer: Vishesh Handa <me@vhanda.in>
    formats:
      - deb
      - rpm
    dependencies:
      - git

publishers:
  - name: fury.io
    ids:
      - linux_packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/vhanda/
