project_name: git-auto-sync

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - binary: git-auto-sync
    id: git-auto-sync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64

  # Macos build needs to be built on macos
  # https://github.com/rjeczalik/notify/issues/177
  - binary: git-auto-sync
    id: git-auto-sync-macos
    env:
      - CGO_ENABLED=1
      - CC=clang
      - CXX=clang++
    goos:
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - README.md
      - completions/bash_autocomplete
      - completions/zsh_autocomplete
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
- name: git-auto-sync
  homepage: https://github.com/GitJournal/homebrew-tap
  tap:
    owner: GitJournal
    name: homebrew-tap
    token: "{{ .Env.TAP_GITHUB_TOKEN }}"
  install: |
    bin.install "git-auto-sync"
    bash_completion.install "completions/bash_autocomplete"
    zsh_completion.install "completions/zsh_autocomplete"
