name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
      branches:
        - "master"

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    env:
      CGO_ENABLED: 0
      EMAIL: test@example.com
      GIT_AUTHOR_NAME: "GitHub CI"
      GIT_COMMITTER_EMAIL: "GitHub CI"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go test ./...

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    env:
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45
